import type { OrvekObject } from "./orvek-types"

const objects: OrvekObject[] = [
  // ─── Receipts ──────────────────────────────────────────────
  {
    id: "r1",
    type: "receipt",
    title: "Let it express itself visually before design.",
    sourceText:
      "Let it express itself visually before we lock the design. I need to see the whole thing standing up first.",
    sourceOrigin: "Voice note · captured",
    date: "2 days ago",
    whyItMatters:
      "Direct evidence for the pattern that visual confirmation precedes architecture lock.",
    relatedIds: ["m-claim-1", "d1"],
    contextIds: ["ctx-self"],
    tags: ["Receipt", "Voice note"],
    evidenceCount: 1,
  },
  {
    id: "r2",
    type: "receipt",
    title: "We need to see everything and see it expressed.",
    sourceText:
      "We need to see everything and see it expressed — every object, every panel — before I trust the shape.",
    sourceOrigin: "ChatGPT archive",
    date: "5 days ago",
    whyItMatters: "Reinforces demand for full feature visibility before commitment.",
    relatedIds: ["m-claim-1", "d1"],
    contextIds: ["ctx-self", "ctx-values"],
    tags: ["Receipt", "Imported"],
    evidenceCount: 1,
  },
  {
    id: "r3",
    type: "receipt",
    title: "I'm not concerned with colours right now.",
    sourceText:
      "I'm not concerned with colours right now. I want the architecture honest before any polish.",
    sourceOrigin: "ChatGPT archive",
    date: "5 days ago",
    whyItMatters: "Separates architecture proof from branding polish in decision framing.",
    relatedIds: ["d1", "m-conflict-4"],
    contextIds: ["ctx-values"],
    tags: ["Receipt", "Imported"],
    evidenceCount: 1,
  },
  {
    id: "r5",
    type: "receipt",
    title: "A previous note about avoiding shipping.",
    sourceText:
      "Maybe I keep refining because shipping makes it real and I'm not ready for it to be judged.",
    sourceOrigin: "ChatGPT archive",
    date: "12 days ago",
    whyResurfaced: "Resurfaced because of a similar decision pattern around the prototype.",
    whyItMatters: "Connects decision avoidance to fear of public judgement.",
    relatedIds: ["m-loop-1", "aq-1", "d-public"],
    contextIds: ["ctx-constraints"],
    tags: ["Receipt", "Resurfaced"],
    evidenceCount: 1,
  },
  {
    id: "r6",
    type: "receipt",
    title: "Need to see everything expressed.",
    sourceText: "Need to see everything expressed before I can stop reopening it.",
    sourceOrigin: "Explore conversation",
    date: "Today",
    whyItMatters: "Links visual expression to the scope-reopening loop.",
    relatedIds: ["m-loop-1", "m-claim-1"],
    contextIds: ["ctx-self"],
    tags: ["Receipt", "From Explore"],
    evidenceCount: 1,
  },

  // ─── Context Profile ───────────────────────────────────────
  {
    id: "ctx-current",
    type: "context",
    title: "Current situation",
    subtype: "context",
    summary:
      "Building Orvek, refining product architecture, balancing design clarity with implementation pressure.",
    whyItMatters:
      "Current situation shapes how much pressure recent decisions carry.",
    receiptIds: ["r2", "r3"],
    supporting: ["Repeated architecture revisions in the last week", "Active build decisions open"],
    whatWouldChange: ["Architecture is locked", "Build pressure eases"],
    tags: ["Current situation", "Editable"],
    evidenceCount: 9,
    lastUpdated: "2 hours ago",
  },
  {
    id: "ctx-values",
    type: "context",
    title: "Values / direction",
    subtype: "context",
    summary:
      "Evidence, self-understanding, agency, building, independence, long-term model improvement.",
    whyItMatters: "Values explain rejection of generic positioning and shallow strategy.",
    receiptIds: ["r3"],
    supporting: ["Consistent preference for inspectable conclusions", "Rejects unbacked claims"],
    tags: ["Values", "Model context"],
    evidenceCount: 14,
    lastUpdated: "1 day ago",
  },
  {
    id: "ctx-interests",
    type: "context",
    title: "Preferences / interests",
    subtype: "context",
    summary:
      "Private intelligence, systems architecture, AI workflows, decision clarity, philosophy, performance.",
    whyItMatters: "Interests bias the product toward depth and systems thinking.",
    supporting: ["Recurring systems-architecture language across receipts"],
    tags: ["Interests", "Background"],
    evidenceCount: 22,
    lastUpdated: "3 days ago",
  },
  {
    id: "ctx-constraints",
    type: "context",
    title: "Constraints",
    subtype: "context",
    summary: "Limited time/energy, pressure to move fast, risk of scope reopening.",
    whyItMatters: "Constraints raise the cost of the scope-reopening loop.",
    receiptIds: ["r5"],
    supporting: ["Scope reopened twice this week", "Stated time pressure"],
    conflicting: ["Still chooses depth over speed when forced"],
    tags: ["Constraints", "Decision context"],
    evidenceCount: 7,
    lastUpdated: "2 hours ago",
  },
  {
    id: "ctx-self",
    type: "context",
    title: "Self-concept / identity context",
    subtype: "context",
    summary:
      "Wants competence, clarity, independence, and a product that compounds over time.",
    whyItMatters: "Identity context explains the need for confidence before locking decisions.",
    receiptIds: ["r1", "r6"],
    supporting: ["Visual confirmation requested before commitment"],
    whatWouldChange: ["Repeated evidence that locking early did not hurt outcomes"],
    tags: ["Self-concept", "Needs review"],
    evidenceCount: 11,
    lastUpdated: "4 hours ago",
  },

  // ─── Map objects: Claims ───────────────────────────────────
  {
    id: "m-claim-1",
    type: "map-object",
    subtype: "claim",
    title: "You often need visual expression before locking architecture.",
    summary:
      "A recurring requirement that the system express itself visually before you commit to a structure.",
    whyItMatters: "Drives the decision to prototype before final design.",
    receiptIds: ["r1", "r2", "r6"],
    supporting: ["3 receipts across two sources", "Consistent over 12 days"],
    conflicting: ["One case where you locked structure from text alone"],
    relatedIds: ["d1", "aq-1", "ctx-self"],
    contextIds: ["ctx-self"],
    whatWouldChange: ["A locked-from-text decision that succeeds", "You report visuals slowed you"],
    tags: ["Claim", "Evidence-backed"],
    evidenceCount: 3,
    lastUpdated: "4 hours ago",
  },
  {
    id: "m-claim-2",
    type: "map-object",
    subtype: "claim",
    title: "You trust systems more when receipts and lineage are visible.",
    summary: "Confidence rises when conclusions can be traced back to source evidence.",
    whyItMatters: "Explains the receipts-everywhere product requirement.",
    receiptIds: ["r2"],
    supporting: ["Repeated requests to see evidence", "Rejection of unbacked claims"],
    relatedIds: ["ctx-values"],
    contextIds: ["ctx-values"],
    whatWouldChange: ["You accept a conclusion without asking for evidence"],
    tags: ["Claim", "Evidence-backed"],
    evidenceCount: 5,
    lastUpdated: "1 day ago",
  },
  {
    id: "m-claim-3",
    type: "map-object",
    subtype: "claim",
    title: "You resist generic AI / journal positioning.",
    summary: "Strong aversion to being categorised as a generic AI or journaling product.",
    whyItMatters: "Shapes category strategy and product language.",
    receiptIds: ["r3"],
    supporting: ["Explicit rejection of shallow strategy"],
    relatedIds: ["ctx-values"],
    contextIds: ["ctx-values"],
    tags: ["Claim", "Evidence-backed"],
    evidenceCount: 4,
    lastUpdated: "2 days ago",
  },

  // ─── Map objects: Conflicts ────────────────────────────────
  {
    id: "m-conflict-1",
    type: "map-object",
    subtype: "conflict",
    title: "Speed vs depth",
    summary: "Pressure to move fast pulls against the need for architectural depth.",
    whyItMatters: "Underlies most current decision tension.",
    relatedIds: ["ctx-constraints", "d1"],
    contextIds: ["ctx-constraints"],
    supporting: ["Stated time pressure", "Repeated depth-first choices"],
    tags: ["Conflict", "Tension"],
    evidenceCount: 6,
    lastUpdated: "2 hours ago",
  },
  {
    id: "m-conflict-2",
    type: "map-object",
    subtype: "conflict",
    title: "Design exploration vs architecture lock",
    summary: "Wanting to explore freely conflicts with the desire to commit a structure.",
    relatedIds: ["d1", "m-claim-1"],
    tags: ["Conflict", "Tension"],
    evidenceCount: 4,
    lastUpdated: "5 hours ago",
  },
  {
    id: "m-conflict-3",
    type: "map-object",
    subtype: "conflict",
    title: "Build now vs research more",
    relatedIds: ["d3"],
    tags: ["Conflict", "Tension"],
    evidenceCount: 3,
    lastUpdated: "1 day ago",
  },
  {
    id: "m-conflict-4",
    type: "map-object",
    subtype: "conflict",
    title: "Polish vs proof",
    summary: "Pull toward visual polish competes with the need for architectural proof.",
    receiptIds: ["r3"],
    relatedIds: ["d1"],
    tags: ["Conflict", "Tension"],
    evidenceCount: 4,
    lastUpdated: "1 day ago",
  },

  // ─── Map objects: Loops ────────────────────────────────────
  {
    id: "m-loop-1",
    type: "map-object",
    subtype: "loop",
    title: "Scope reopening under uncertainty",
    summary:
      "When uncertainty rises, scope reopens rather than narrows — extending the build.",
    whyItMatters: "The most active loop; directly raises decision pressure.",
    receiptIds: ["r5", "r6"],
    supporting: ["Scope reopened twice this week", "Linked to public-test avoidance"],
    conflicting: ["One instance of narrowing scope under pressure"],
    relatedIds: ["aq-1", "ctx-constraints", "d-public"],
    contextIds: ["ctx-constraints"],
    whatWouldChange: ["A narrow test ships without reopening scope"],
    tags: ["Loop", "Active"],
    evidenceCount: 6,
    lastUpdated: "2 hours ago",
  },
  {
    id: "m-loop-2",
    type: "map-object",
    subtype: "loop",
    title: "Rechecking decisions before visual confirmation",
    summary: "Decisions get re-examined until the system can be seen, not just described.",
    receiptIds: ["r1"],
    relatedIds: ["m-claim-1", "d1"],
    tags: ["Loop", "Active"],
    evidenceCount: 4,
    lastUpdated: "4 hours ago",
  },
  {
    id: "m-loop-3",
    type: "map-object",
    subtype: "loop",
    title: "Rejecting generic strategy when it feels amateur",
    receiptIds: ["r3"],
    relatedIds: ["m-claim-3"],
    tags: ["Loop", "Active"],
    evidenceCount: 3,
    lastUpdated: "2 days ago",
  },

  // ─── Map objects: Model Goals ──────────────────────────────
  {
    id: "m-goal-1",
    type: "model-goal",
    subtype: "goal",
    title: "Build Orvek into a private intelligence system",
    summary: "Make Orvek a durable private intelligence system.",
    whyItMatters: "Sets the long-term build direction.",
    relatedIds: ["ctx-current"],
    tags: ["Model Goal"],
    evidenceCount: 8,
    lastUpdated: "2 hours ago",
    whatWouldChange: ["Capture correction in Capture Life Data"],
  },
  {
    id: "m-goal-2",
    type: "model-goal",
    subtype: "goal",
    title: "Create a defensible product category",
    summary: "The product category should be defensible and inspectable.",
    whyItMatters: "Keeps the product from collapsing into generic productivity tooling.",
    relatedIds: ["m-claim-3"],
    tags: ["Model Goal"],
    evidenceCount: 5,
    lastUpdated: "1 day ago",
    whatWouldChange: ["Capture correction in Capture Life Data"],
  },
  {
    id: "m-goal-3",
    type: "model-goal",
    subtype: "goal",
    title: "Move from architecture to prototype without losing depth",
    summary: "Ship a prototype without flattening the underlying model.",
    whyItMatters: "Preserves build depth while shipping.",
    relatedIds: ["d1", "m-conflict-1"],
    tags: ["Model Goal"],
    evidenceCount: 6,
    lastUpdated: "3 hours ago",
    whatWouldChange: ["Capture correction in Capture Life Data"],
  },

  // ─── Active questions ──────────────────────────────────────
  {
    id: "aq-1",
    type: "active-question",
    title: "Does public visibility trigger overbuilding?",
    summary: "Testing whether anticipated visibility drives scope reopening.",
    whyItMatters: "If true, narrowing exposure could break the loop.",
    receiptIds: ["r5"],
    supporting: ["New evidence from decision and fieldwork"],
    missingEvidence: ["A public test result"],
    relatedIds: ["m-loop-1", "d-public", "f1"],
    status: "active",
    tags: ["Active Question"],
    evidenceCount: 4,
    lastUpdated: "Today",
  },
  {
    id: "aq-2",
    type: "active-question",
    title: "Does visual prototyping reduce architecture uncertainty?",
    summary: "Whether a v0 prototype meaningfully lowers uncertainty before design.",
    receiptIds: ["r1", "r6"],
    missingEvidence: ["Prototype result"],
    relatedIds: ["d1", "f1", "inv-2"],
    status: "active",
    tags: ["Active Question"],
    evidenceCount: 3,
    lastUpdated: "Today",
  },
  {
    id: "aq-3",
    type: "active-question",
    title: "Which features are essential for first public value?",
    status: "open",
    relatedIds: ["m-goal-2"],
    tags: ["Active Question"],
    evidenceCount: 2,
    lastUpdated: "Yesterday",
  },
  {
    id: "aq-4",
    type: "active-question",
    title: "How should Explore extract model-relevant gold from conversation?",
    relatedIds: ["inv-3"],
    status: "open",
    tags: ["Active Question"],
    evidenceCount: 2,
    lastUpdated: "Yesterday",
  },

  // ─── Model updates ─────────────────────────────────────────
  {
    id: "mu-1",
    type: "model-update",
    title: "Decision pressure is now linked to scope reopening.",
    summary:
      "Orvek connected rising decision pressure to the scope-reopening loop using six receipts.",
    whyItMatters: "Reframes pressure as a structural loop rather than a mood.",
    receiptIds: ["r5", "r6"],
    before: "Decision pressure was treated as an isolated state.",
    after: "Decision pressure is modeled as an output of the scope-reopening loop.",
    relatedIds: ["m-loop-1", "aq-1"],
    tags: ["Model Update"],
    evidenceCount: 6,
    lastUpdated: "2 hours ago",
  },
  {
    id: "mu-2",
    type: "model-update",
    title: "User Background / Context Profile added as core model layer",
    summary: "Context Profile promoted from metadata to a first-class, correctable model layer.",
    before: "Map owned claims, conflicts, loops, model goals, active questions.",
    after: "Map also owns User Background / Context Profile as part of the readable model.",
    receiptIds: ["r2"],
    relatedIds: ["ctx-current", "ctx-values"],
    tags: ["Model Update"],
    evidenceCount: 3,
    lastUpdated: "2 hours ago",
  },
  {
    id: "mu-3",
    type: "model-update",
    title: "Explore expanded beyond investigations",
    summary: "Explore now supports free model-aware conversation plus extraction.",
    relatedIds: ["inv-3"],
    tags: ["Model Update"],
    evidenceCount: 2,
    lastUpdated: "This week",
  },
  {
    id: "mu-4",
    type: "model-update",
    title: "Timeline must be visual from V1",
    tags: ["Model Update"],
    evidenceCount: 1,
    lastUpdated: "This week",
  },
  {
    id: "mu-5",
    type: "model-update",
    title: "Reports require viewer / history",
    tags: ["Model Update"],
    evidenceCount: 1,
    lastUpdated: "This week",
  },

  // ─── Decisions ─────────────────────────────────────────────
  {
    id: "d1",
    type: "decision",
    title: "Use v0 architecture prototype before final design",
    summary:
      "Should we create a visual architecture prototype in v0 before locking design?",
    recommendation:
      "Likely yes. Visual prototyping should expose missing flows before final design polish.",
    options: [
      { label: "A", text: "Go straight to design document." },
      {
        label: "B",
        text: "Generate v0 architecture prototype first.",
        pros: [
          "Exposes layout issues",
          "Tests the right panel",
          "Shows feature density",
          "Helps lock architecture",
          "Avoids premature branding polish",
        ],
        cons: [
          "v0 may flatten the concept",
          "May over-focus on visual dashboard",
          "Needs careful prompt",
          "May create false confidence",
        ],
      },
      { label: "C", text: "Do more research first." },
    ],
    decisionContext: [
      { label: "Emotional context", value: "Wants confidence before locking" },
      { label: "Environmental context", value: "Architecture just changed with Context Profile" },
      { label: "Timing context", value: "Before design phase" },
      { label: "Pressure state", value: "Avoid losing details" },
    ],
    contextIds: ["ctx-self", "ctx-values", "ctx-current"],
    receiptIds: ["r1", "r2", "r3"],
    projection:
      "Creating the v0 prototype should reveal missing page responsibilities and reduce uncertainty before design.",
    confidence: "Medium-high",
    whatWouldChange: [
      "If v0 produces generic dashboard UI",
      "If prototype hides too many objects",
      "If right panel cannot represent the evidence model",
    ],
    outcomeWindow: "Review after first v0 prototype.",
    outcomeState: "open",
    relatedIds: ["m-claim-1", "m-conflict-1", "aq-2", "f1"],
    tags: ["Decision", "Active"],
    evidenceCount: 3,
    lastUpdated: "Today",
  },
  {
    id: "d2",
    type: "decision",
    title: "Lock feature architecture before visual design",
    summary: "Whether to freeze the feature architecture before any visual design work.",
    recommendation: "Conditional — lock once the prototype confirms page responsibilities.",
    decisionContext: [{ label: "Pressure state", value: "Wants to stop reopening scope" }],
    relatedIds: ["m-loop-1", "d1"],
    outcomeState: "open",
    confidence: "Medium",
    tags: ["Decision", "Active"],
    evidenceCount: 2,
    lastUpdated: "Today",
  },
  {
    id: "d3",
    type: "decision",
    title: "Prioritise import or Explore refinement?",
    summary: "Where to spend the next build cycle: import pipeline or Explore extraction.",
    recommendation: "Lean import — it feeds every other surface with evidence.",
    relatedIds: ["mu-3", "imp-1"],
    outcomeState: "open",
    confidence: "Low-medium",
    tags: ["Decision", "Active"],
    evidenceCount: 2,
    lastUpdated: "Yesterday",
  },
  {
    id: "d-public",
    type: "decision",
    title: "Small public test",
    summary: "Test one narrow version publicly before reopening the whole system.",
    recommendation: "Yes — a narrow test directly probes the scope-reopening loop.",
    decisionContext: [{ label: "Emotional context", value: "Public judgement raises avoidance" }],
    contextIds: ["ctx-constraints"],
    receiptIds: ["r5"],
    projection: "A narrow public test should reveal whether visibility triggers overbuilding.",
    confidence: "Medium",
    outcomeWindow: "Check in today.",
    outcomeState: "due",
    expectedOutcome: "Ship a narrow test without reopening scope.",
    relatedIds: ["m-loop-1", "aq-1", "f1"],
    tags: ["Decision", "Outcome due"],
    evidenceCount: 3,
    lastUpdated: "Today",
  },
  {
    id: "d-nav",
    type: "decision",
    title: "Decision page as top-level nav",
    summary: "Whether Decisions deserves a primary nav slot.",
    recommendation: "Yes — decisions create the learning loop.",
    outcomeState: "due",
    expectedOutcome: "Decisions used as a daily workspace, not an occasional list.",
    relatedIds: ["mu-1"],
    tags: ["Decision", "Outcome due"],
    evidenceCount: 1,
    lastUpdated: "Yesterday",
  },
  {
    id: "d-rev-1",
    type: "decision",
    title: "Move User Investigations into Explore",
    summary: "Investigations folded into Explore rather than a separate page.",
    recommendation: "Confirmed.",
    outcomeState: "recorded",
    expectedOutcome: "Fewer top-level pages, investigations stay close to conversation.",
    actualOutcome: "Investigations now live inside Explore and feel more connected.",
    relatedIds: ["mu-3", "inv-1"],
    tags: ["Decision", "Reviewed"],
    evidenceCount: 2,
    lastUpdated: "This week",
  },
  {
    id: "d-rev-2",
    type: "decision",
    title: "Remove Calendar from V1",
    summary: "Calendar dropped from V1 scope.",
    recommendation: "Confirmed.",
    outcomeState: "recorded",
    expectedOutcome: "Less planner identity, more intelligence identity.",
    actualOutcome: "Removing Calendar sharpened the product's identity.",
    tags: ["Decision", "Reviewed"],
    evidenceCount: 1,
    lastUpdated: "This week",
  },
  {
    id: "d-rev-3",
    type: "decision",
    title: "Keep Reports as output layer",
    summary: "Reports stay a cross-system output rather than a nav page.",
    recommendation: "Confirmed.",
    outcomeState: "recorded",
    expectedOutcome: "Reports feel core without crowding nav.",
    actualOutcome: "Reports remain accessible from Today and Timeline.",
    relatedIds: ["mu-5"],
    tags: ["Decision", "Reviewed"],
    evidenceCount: 1,
    lastUpdated: "This week",
  },

  // ─── Reports ───────────────────────────────────────────────
  {
    id: "rep-weekly",
    type: "report",
    title: "Weekly Model Movement",
    reportType: "Weekly Report",
    period: "This week",
    reportSummary: "3 repeated loops, 2 decisions, 1 context profile update.",
    summary:
      "Your model shifted around launch pressure, decision avoidance, and public testing.",
    receiptIds: ["r5", "r6", "r2"],
    relatedIds: ["mu-1", "mu-2", "m-loop-1", "d1", "ctx-current"],
    tags: ["Report", "This week"],
    evidenceCount: 11,
    lastUpdated: "Today",
  },
  {
    id: "rep-changed",
    type: "report",
    title: "What Changed",
    reportType: "What Changed",
    period: "Last 24 hours",
    reportSummary: "4 model changes across decisions, loops, and context.",
    summary: "The newest movement in your model, ranked by evidence.",
    relatedIds: ["mu-1", "mu-2"],
    tags: ["Report", "Today"],
    evidenceCount: 6,
    lastUpdated: "2 hours ago",
  },
  {
    id: "rep-decision",
    type: "report",
    title: "Decision Review",
    reportType: "Decision Review",
    period: "This week",
    reportSummary: "12 decisions reviewed, 5 calibration signals.",
    summary: "How recent decisions tracked against their projections.",
    relatedIds: ["d-rev-1", "d-rev-2", "d-rev-3"],
    tags: ["Report", "This week"],
    evidenceCount: 8,
    lastUpdated: "Yesterday",
  },
  {
    id: "rep-fieldwork",
    type: "report",
    title: "Fieldwork Result",
    reportType: "Fieldwork Result",
    period: "Pending",
    reportSummary: "Awaiting first prototype check-in.",
    summary: "Results from real-world tests linked to open questions.",
    relatedIds: ["f1", "aq-2"],
    tags: ["Report", "Pending"],
    evidenceCount: 1,
    lastUpdated: "Today",
  },
  {
    id: "rep-resurfaced",
    type: "report",
    title: "Receipts Resurfaced",
    reportType: "Receipts Resurfaced",
    period: "This week",
    reportSummary: "2 older receipts became relevant again.",
    summary: "Past evidence that re-entered the active model.",
    receiptIds: ["r5"],
    relatedIds: ["m-loop-1"],
    tags: ["Report", "This week"],
    evidenceCount: 3,
    lastUpdated: "Today",
  },
  {
    id: "rep-stress",
    type: "report",
    title: "Feature Architecture Stress Test",
    reportType: "Stress Test",
    period: "Today",
    reportSummary: "Architecture audited against all five surfaces.",
    summary: "Page responsibilities and right-panel coverage checked across object types.",
    relatedIds: ["d1", "mu-2"],
    tags: ["Report", "Today"],
    evidenceCount: 4,
    lastUpdated: "Today",
  },

  // ─── Fieldwork ─────────────────────────────────────────────
  {
    id: "f1",
    type: "fieldwork",
    title: "Small public test",
    purpose: "Test one narrow version before reopening the whole system.",
    expectedSignal: "Whether anticipated visibility triggers scope reopening.",
    whatToObserve: "Did you narrow the test, or expand it before shipping?",
    confirmIf: "You ship a narrow test without reopening scope.",
    weakenIf: "You reopen scope to make the test 'complete' first.",
    reviewWindow: "Due today",
    resultHistory: ["Created from the public-test decision"],
    relatedIds: ["d-public", "aq-1", "m-loop-1"],
    contextIds: ["ctx-constraints"],
    tags: ["Fieldwork", "Due today"],
    evidenceCount: 2,
    lastUpdated: "Today",
  },
  {
    id: "f2",
    type: "fieldwork",
    title: "Test architecture visually in v0",
    purpose: "Generate a v0 architecture prototype and review against feature architecture.",
    expectedSignal: "Whether the prototype reduces uncertainty or creates false confidence.",
    whatToObserve: "Which page overloads first? Does the right panel cover every object type?",
    confirmIf: "Missing flows become obvious and uncertainty drops.",
    weakenIf: "The prototype flattens the concept into a generic dashboard.",
    reviewWindow: "Review after first prototype",
    relatedIds: ["d1", "aq-2", "inv-2"],
    tags: ["Fieldwork", "Created"],
    evidenceCount: 1,
    lastUpdated: "Yesterday",
  },

  // ─── Investigations ────────────────────────────────────────
  {
    id: "inv-1",
    type: "investigation",
    title: "Why do I reopen scope before design?",
    whyItMatters: "Understanding the trigger could break the most expensive loop.",
    status: "active",
    receiptIds: ["r5", "r6"],
    hypotheses: [
      "Visibility raises the stakes and triggers overbuilding.",
      "Uncertainty feels safer to expand than to narrow.",
    ],
    missingEvidence: ["A prototype result", "A shipped narrow test"],
    relatedIds: ["m-loop-1", "aq-1", "f1"],
    contextIds: ["ctx-constraints"],
    tags: ["Investigation", "Active"],
    evidenceCount: 8,
    lastUpdated: "Today",
  },
  {
    id: "inv-2",
    type: "investigation",
    title: "Does visual prototyping reduce architecture uncertainty?",
    whyItMatters:
      "If prototyping reliably reduces uncertainty, it should become a standard pre-design step.",
    status: "active",
    receiptIds: ["r1", "r6"],
    hypotheses: [
      "Seeing the system standing up exposes missing flows.",
      "Prototypes can create false confidence if they flatten the concept.",
    ],
    missingEvidence: ["Prototype result", "Gap audit after prototype"],
    relatedIds: ["d1", "f2", "aq-2"],
    contextIds: ["ctx-self"],
    tags: ["Investigation", "Active"],
    evidenceCount: 5,
    lastUpdated: "Today",
  },
  {
    id: "inv-3",
    type: "investigation",
    title: "How should Explore extract useful model data from conversation?",
    whyItMatters: "Extraction quality determines how much conversation becomes model movement.",
    status: "open",
    hypotheses: ["Extract receipts, context updates, questions, and fieldwork separately."],
    missingEvidence: ["Labeled examples of good vs noise extraction"],
    relatedIds: ["mu-3", "aq-4"],
    tags: ["Investigation", "Open"],
    evidenceCount: 3,
    lastUpdated: "Yesterday",
  },

  // ─── Timeline events ───────────────────────────────────────
  {
    id: "t1",
    type: "timeline-event",
    eventType: "Model Update",
    title: "User Background / Context Profile added to system architecture",
    date: "Today · 09:14",
    affectedObject: "Map · Context Profile",
    summary: "Context Profile promoted to a core, correctable model layer.",
    before: "Map owned claims, conflicts, loops, model goals, active questions.",
    after: "Map also owns User Background / Context Profile as part of the readable model.",
    receiptIds: ["r2"],
    relatedIds: ["mu-2", "ctx-current"],
    tags: ["Model Update"],
    evidenceCount: 3,
  },
  {
    id: "t2",
    type: "timeline-event",
    eventType: "Decision",
    title: "Use v0 prototype before final design",
    date: "Today · 08:40",
    affectedObject: "Decision",
    summary: "Decision opened to prototype architecture before design lock.",
    relatedIds: ["d1"],
    tags: ["Decision"],
    evidenceCount: 3,
  },
  {
    id: "t3",
    type: "timeline-event",
    eventType: "Report",
    title: "Feature architecture stress test completed",
    date: "Today · 08:05",
    affectedObject: "Report",
    relatedIds: ["rep-stress"],
    tags: ["Report"],
    evidenceCount: 4,
  },
  {
    id: "t4",
    type: "timeline-event",
    eventType: "Capture",
    title: "Voice note added about design path",
    date: "Today · 07:52",
    affectedObject: "Receipt",
    relatedIds: ["r1"],
    tags: ["Capture"],
    evidenceCount: 1,
  },
  {
    id: "t5",
    type: "timeline-event",
    eventType: "Receipt resurfaced",
    title: "Visual expression needed before locking architecture",
    date: "Yesterday · 18:20",
    affectedObject: "Receipt",
    whyResurfaced: "Similar decision pattern detected.",
    relatedIds: ["r6", "m-claim-1"],
    tags: ["Receipt"],
    evidenceCount: 1,
  },
  {
    id: "t6",
    type: "timeline-event",
    eventType: "Active Question updated",
    title: "Does prototype reduce uncertainty?",
    date: "Yesterday · 16:02",
    affectedObject: "Active Question",
    relatedIds: ["aq-2"],
    tags: ["Active Question"],
    evidenceCount: 3,
  },
  {
    id: "t7",
    type: "timeline-event",
    eventType: "Fieldwork created",
    title: "Test architecture visually in v0",
    date: "Yesterday · 15:30",
    affectedObject: "Fieldwork",
    relatedIds: ["f2"],
    tags: ["Fieldwork"],
    evidenceCount: 1,
  },
  {
    id: "t8",
    type: "timeline-event",
    eventType: "Import",
    title: "ChatGPT archive processed",
    date: "This week · Mon",
    affectedObject: "Import",
    summary: "18,582 messages processed; 243 receipts extracted.",
    relatedIds: ["imp-1"],
    tags: ["Import"],
    evidenceCount: 243,
  },
  {
    id: "t9",
    type: "timeline-event",
    eventType: "Report",
    title: "Weekly Model Movement generated",
    date: "This week · Mon",
    affectedObject: "Report",
    relatedIds: ["rep-weekly"],
    tags: ["Report"],
    evidenceCount: 11,
  },
  {
    id: "t10",
    type: "timeline-event",
    eventType: "Decision reviewed",
    title: "User Investigations belong inside Explore",
    date: "This week · Tue",
    affectedObject: "Decision",
    relatedIds: ["d-rev-1"],
    tags: ["Decision"],
    evidenceCount: 2,
  },
  {
    id: "t11",
    type: "timeline-event",
    eventType: "Map update",
    title: "Explore expanded beyond investigations",
    date: "This week · Wed",
    affectedObject: "Map",
    relatedIds: ["mu-3"],
    tags: ["Model Update"],
    evidenceCount: 2,
  },
  {
    id: "t12",
    type: "timeline-event",
    eventType: "Decision",
    title: "Calendar removed from V1",
    date: "Earlier",
    affectedObject: "Decision",
    relatedIds: ["d-rev-2"],
    tags: ["Decision"],
    evidenceCount: 1,
  },
  {
    id: "t13",
    type: "timeline-event",
    eventType: "Decision",
    title: "Decisions promoted to top-level nav",
    date: "Earlier",
    affectedObject: "Decision",
    relatedIds: ["d-nav"],
    tags: ["Decision"],
    evidenceCount: 1,
  },
  {
    id: "t14",
    type: "timeline-event",
    eventType: "Decision",
    title: "Reports kept as output layer",
    date: "Earlier",
    affectedObject: "Decision",
    relatedIds: ["d-rev-3"],
    tags: ["Decision"],
    evidenceCount: 1,
  },

  // ─── Import (for reference panel links) ────────────────────
  {
    id: "imp-1",
    type: "report",
    title: "ChatGPT archive import",
    reportType: "Import Source",
    period: "This week",
    reportSummary: "18,582 messages · 243 receipts · 18 objects · 7 questions.",
    summary: "Source archive that seeded the current model.",
    relatedIds: ["t8", "rep-resurfaced"],
    tags: ["Import"],
    evidenceCount: 243,
    lastUpdated: "This week",
  },
]

export const OBJECTS: Record<string, OrvekObject> = Object.fromEntries(
  objects.map((o) => [o.id, o]),
)

export function getObject(id: string | null | undefined): OrvekObject | undefined {
  if (!id) return undefined
  return OBJECTS[id]
}

export function getObjects(ids: string[] | undefined): OrvekObject[] {
  if (!ids) return []
  return ids.map((id) => OBJECTS[id]).filter(Boolean) as OrvekObject[]
}

/**
 * Possible model movement surfaced live by an Explore conversation.
 * Read by both the Explore page and the inspector's Model Movement tab.
 */
export interface ExploreMovement {
  id: string
  kind: string
  text: string
  /** related object the proposal would attach to */
  linkId?: string
}

export const EXPLORE_MOVEMENT: ExploreMovement[] = [
  {
    id: "ex1",
    kind: "Receipt extracted",
    text: "Need to see architecture visually before final design.",
    linkId: "r6",
  },
  {
    id: "ex2",
    kind: "Context Profile update",
    text: "User prefers visual stress-testing before locking product design.",
    linkId: "ctx-values",
  },
  {
    id: "ex3",
    kind: "Active Question proposed",
    text: "Does prototype output reduce uncertainty or create false confidence?",
    linkId: "aq-2",
  },
  {
    id: "ex4",
    kind: "Fieldwork proposed",
    text: "Generate v0 architecture prototype and audit missing flows.",
    linkId: "f2",
  },
]

/** Receipts/map objects the live conversation is currently grounded in. */
export const EXPLORE_GROUNDING = ["d1", "m-claim-1", "r6", "aq-2", "ctx-values"]
