export const PHASE2_OBJECTIVITY_CONSTANTS = {
  UMAP_MIN_EVIDENCE_EMERGING: 2,
  UMAP_MIN_SOURCE_TYPES_EMERGING: 2,
  UMAP_MIN_EVIDENCE_SUPPORTED: 4,
  UMAP_MIN_SOURCE_TYPES_SUPPORTED: 2,
  UMAP_MIN_TIME_SPREAD_DAYS_SUPPORTED: 7,

  UMAP_CONF_CAP_2_EVIDENCE: 0.3,
  UMAP_CONF_CAP_3_TO_5_EVIDENCE: 0.5,
  UMAP_CONF_CAP_6_TO_10_EVIDENCE: 0.7,
  UMAP_CONF_CAP_10_PLUS_EVIDENCE: 0.85,

  SINGLE_EPISODE_SUPPORTED_BLOCK: true,
  HIGH_EMOTION_STATUS_CAP: "emerging" as const,
  HIGH_EMOTION_IDENTITY_CLAIM_BLOCK: true,
  LANGUAGE_OVERCLAIMING_BLOCK: true,
  RECEIPT_REQUIRED_FOR_PROMOTION: true,

  MODEL_UPDATE_REQUIRES_MEANINGFUL_DELTA: true,
  MODEL_UPDATE_REQUIRES_EVIDENCE_LINK: true,
  MODEL_UPDATE_MIN_CONF_DELTA: 0.08,
  MODEL_UPDATE_BLOCK_SYNTHETIC_DAILY_INSIGHT: true,

  CORRECTION_CONFIDENCE_MULTIPLIER: 0.5,

  PROFILE_ARTIFACT_MIN_CONTRIBUTION: 0.25,
  PROFILE_ARTIFACT_MAX_CONTRIBUTION: 0.45,

  HIGH_EMOTION_DOMINANCE_RATIO: 0.5,
  LOW_QUOTE_MIN_LENGTH: 12,
} as const;

export const NON_LINKABLE_CONTEXT_SOURCE_TYPES = [
  "timeline_aggregation",
  "user_correction",
] as const;

export const ACTIVE_CONTRADICTION_STATUSES = [
  "candidate",
  "open",
  "snoozed",
  "explored",
] as const;

export const REJECTION_REASON_CODES = [
  "INSUFFICIENT_EVIDENCE_COUNT",
  "INSUFFICIENT_SOURCE_DIVERSITY",
  "INSUFFICIENT_TIME_SPREAD",
  "HIGH_EMOTION_DOMINANCE_CAP",
  "HIGH_EMOTION_IDENTITY_BLOCK",
  "SINGLE_EPISODE_SUPPORTED_BLOCK",
  "MISSING_PROVENANCE",
  "NON_LINKABLE_CONTEXT_ONLY",
  "LOW_QUOTE_QUALITY",
  "PROFILE_ARTIFACT_CAP",
  "DISCONFIRMATION_UNRESOLVED",
  "CORRECTION_DOWNGRADE_ACTIVE",
  "NO_MEANINGFUL_DELTA",
  "SYNTHETIC_INSIGHT_BLOCKED",
  "LANGUAGE_OVERCLAIMING_BLOCKED",
] as const;

export type RejectionReasonCode = (typeof REJECTION_REASON_CODES)[number];
